### ISSUE TITLE
Remove auth_token from UserSerializer

### ISSUE THREAD

**Issue by glemmaPaul** [agconti/cookiecutter-django-rest#104]
I'm not sure if intended, but `auth_token` is in the response `GET /users/`.

**Comment by agconti** [comment]
@glemmaPaul  This was originally intended for an app that restricted user list and detail with an isOwner permission. 

Rather than implement an isOwner permission here, I agree that it makes more sense to remove it from user list and detail. Especially since a user's `auth_token` can always be retrieved at `api-token-auth/` and users will get it when they register. 

Great catch, thanks!
