### ISSUE TITLE
Do super() in test case of users 

### ISSUE THREAD

**Issue by glemmaPaul** [agconti/cookiecutter-django-rest#106]
Just so that super classes can do their thing.
https://github.com/agconti/cookiecutter-django-rest/blob/master/%7B%7Bcookiecutter.github_repository_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/users/test/test_views.py#L18

**Comment by agconti** [comment]
@glemmaPaul thanks for point this out. I'm really surprised that all of the calls to `self.client` don't throw an error. Excited to dig into this.

**Comment by glemmaPaul** [comment]
Oh damn @agconti I didn't even notice that! That is indeed interesting how that keeps on going

**Comment by agconti** [comment]
@glemmaPaul there's no `setUp` method in DRF's [`APITestCase`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/test.py#L134-L215), so there is nothing to `super`. Is there something else you think we should call `super` on? 

Closing this for since the inheritance is working as intended.
