### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by thubamamba** [agconti/cookiecutter-django-rest#1600]
I am new to the awesome `cookiecutter-django-rest`. I keep having problems installing additional packages using docker. Is there something I am missing with how to go about this?

![CleanShot 2022-06-24 at 13 31 53](https://user-images.githubusercontent.com/22769109/175526273-81cbf55f-16e2-4eb9-8618-ba7245d9f138.png)

When I install via pip, I get `ModuleNotFoundError: No module named 'drf_yasg'`.

**Comment by agconti** [comment]
@thubamamba closing this issue since it's not related to this project but rather a general question on how do I work with a project that uses docker. 

You can add packages to your project by:

1. Add the package to the project's requirements.txt file.
2. Stop your current compose stack if you have one running: `docker-compose down`
3. Build the web container so that the new package is installed in the image: `docker-compose build web`
4. Start your compose stack again: `docker-compose up`
