### ISSUE TITLE
Add jwt and oauth2 for third parties (social)

### ISSUE THREAD

**Issue by musicformellons** [agconti/cookiecutter-django-rest#239]
It would be nice to have these added as these are troublesome setting up for DRF.

**Comment by agconti** [comment]
Hi @musicformellons, thanks for your question.

Adding jwt support was considered in #146 but was [decided against](https://github.com/agconti/cookiecutter-django-rest/pull/146#issuecomment-205039612) so that this project could stay lean and minimally opinionated. 

There's actually robust and easy jwt support for DRF. I recommend using [django-rest-framework-jwt](https://github.com/GetBlimp/django-rest-framework-jwt); its an awesome package. Oauth2 is much the same. I recommend [python-social-auth](https://github.com/python-social-auth/social-app-django) .
