### ISSUE TITLE
CORS 

### ISSUE THREAD

**Issue by israeleriston** [agconti/cookiecutter-django-rest#364]
Hello, what is the possibility of adding COLORS to this project, I needed it, so I thought I would contribute.
see https://github.com/ottoyiu/django-cors-headers

**Comment by israeleriston** [comment]
@agconti, i can contributor to implementation of issue #364 ?

**Comment by agconti** [comment]
Hey @israeleriston, thanks for proposing this and offering to contribute! ✨ 😊

The idea behind this project is to have the slimmest possible boilerplate while maximizing developer productivity from the get go. `CORS` isn't something that I think the project should support out of the box because it's a specific application use case. While many will find it useful, many others wont have a need for it. 

If this is something that you'd like to maintain yourself -- I encourage you to fork the project!
