### ISSUE TITLE
Missing makemigrations in Dockerfile

### ISSUE THREAD

**Issue by TAnas0** [agconti/cookiecutter-django-rest#548]
Hi,

I am trying to use this template and customize it for my personal needs.
I noticed that the Dockerfile misses a command to generate migrations (`./manage.py makemigrations`) before applying them (`./manage migrate`).

After adding a new model, I am left in need of accessing the command line and making the migrations manually for them to be taken into account.

It should be noted that I prefered using Django 1.11 for it being a LTS release. I checked if this has anything to do with Django's version but did not come to any conclusion.

It is probable that I am doing something wrong, even though I tried many times. Maybe I am missing something obvious.

Thanks

**Comment by MrGreenTea** [comment]
Why should the docker container make the migrations? They should be in your VCS anyways...

**Comment by agconti** [comment]
Hey @TAnas0, thanks for opening up an issue!

This is intentional; we don't want to create migrations automatically. 

As @MrGreenTea pointed out, your migrations should be in version control. Additionally the developer should take care of how and when these migrations are created so that the resulting table alters are reasonable. For example, if we ran `makemigrations` on every restart; we'd have migration for every time we save and make a model change. This could be many many changes, typos, and mistakes. We'd really only want to record a single change for new schema we desire at that point in time. Also, not all changes can be handled automatically by django's migrations. Some alters need data migrations to work. Others, like renaming primary keys,  need multiple carefully thought out migration steps.
