### ISSUE TITLE
Move configuration outside project root

### ISSUE THREAD

**Issue by ferndot** [agconti/cookiecutter-django-rest#570]
In _Two Scoops of Django_, it is recommended to move configuration files outside of the primary project directory and into their own `config` directory. This cleans and simplifies the directory structure and preserves the logical gap between configuration and app logic.

I make this change each time I use this cookiecutter. Here's a PR just in case you're interested.

**Comment by dnk8n** [comment]
I recently had good experience using [django-environ](https://django-environ.readthedocs.io/en/latest/). It allowed both my docker-compose and my Django application to reference the same .env file.


Is that the kind of thing that this issue could benefit from? I may be misinterpreting.

**Comment by ferndot** [comment]
@dnk8n this particular issue is just referring to a change in project structure. However, django-environ is also quite useful and could merit its own issue.

**Comment by agconti** [comment]
@joshua-s pydanny is great and I'm a personal fan of Two Scoops of Django. 

Two Scoop's is pydanny's personal perspective and opinions on how to develop and structure a Django project. If you like his style better, I suggest you use [cookiecutter-django](https://github.com/pydanny/cookiecutter-django). 

To your point: 

> This cleans and simplifies the directory structure and preserves the logical gap between configuration and app logic.

I think this project's current setup, where all the project's configuration is under `/config`, does that much better than your suggested refactor. 

ie. 

```
wsgi.py
config/ 
  common.py
  local.py
  production.py
```

vs

```
config/
  wsgi.py
  settings/ 
    common.py
    local.py
    production.py
```

Nesting the configuration files by an additional folder doesn't add any semantic or organizational value imo. Including `wsgi.py` is strange because it's not a configuration file. It's your server definition, though that's hard to see with how much magic happens there. If you're familiar, it's identical to the `index.js` or `server.js` of a Node project. It's not configuration; its part of your application code. In my opinion, this is why the `django-admin startproject` leaves it at the project's root. In contrast to pydanny, my personal opinion is that folder nesting should be avoided when possible. It makes things organizationally easier. It makes importing easier. 

If you truly like this file structure better; that's fantastic. Be careful though of feeling like pydanny's way is the _right_ way because of two scoops of Django. His options and perspective are great, but at the end of the day, they're just his personal values that you should evaluate for yourself. 

I'm going to close this issue for these reasons.  As always, if you like this project but it's not perfectly matched to your own style; please fork it! Thank you for contributing 💖

**Comment by ferndot** [comment]
Thank you for the clear and well-reasoned response @agconti! I think you make a very good point.

This cookiecutter is lovely and saved me a great deal of time. Thanks for putting your effort into it!
