### ISSUE TITLE
`docker-compose up` goes into an infinite loop on Docker Desktop for Windows 10 Pro

### ISSUE THREAD

**Issue by znmeb** [agconti/cookiecutter-django-rest#903]
#### What's going wrong?
When I do `docker compose up` the containers start, but the "web_1" container goes into a non-ending loop repeating

```
web_1            | Postgres is ready! ✨ 💅
web_1            | /usr/bin/env: ‘python\r’: No such file or directory
web_1            | Postgres is ready! ✨ 💅
web_1            | /usr/bin/env: ‘python\r’: No such file or directory
windows-docker-test_web_1 exited with code 127
web_1            | Postgres is ready! ✨ 💅
web_1            | /usr/bin/env: ‘python\r’: No such file or directory
windows-docker-test_web_1 exited with code 127
web_1            | Postgres is ready! ✨ 💅
```

This does not happen on a Linux Docker host, and I have a fix!

#### How can the `cookiecutter-django-rest` team reproduce the problem?
1. Get a Windows 10 Pro system and install Docker Desktop. I've heard reports this also happens with the VirtualBox "Docker Toolbox" distribution but I only have the current one.
2. Install Git for Windows and Python. I use Anaconda 3 but this isn't a Python problem.
3. Create a virtual environment and install `cookiecutter`. Again, I used `conda` and installed `cookiecutter` from the `conda-forge` channel. Version is
```
Cookiecutter 1.7.0 from C:\Users\znmeb\miniconda3\envs\cookiecutter\lib\site-packages (Python 2.7)
```
4. Create a project scaffold
5. `cd` into the project and type `docker-compose up`.

#### Is this a problem with a fresh install of the project?
- [ x] Yes

***

OK ... the cause is that Git for Windows checks text files out with a `CRLF` line ending code by default. This is fine on Windows but when those files get sent to a Docker container the Linux shell interpreter in the container may not be able to interpret them correctly. That's what's happening here with `manage.py`.

So you need a `.gitattributes` file in the repository that specifies checking out all text files destined for a container with Unix line endings (`LF`). See <https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings> for the documentation.

**Comment by znmeb** [comment]
Here's where we ran into it - our `.gitattributes` file works: https://github.com/Pand-Aid/pandaid-api/issues/4

**Comment by agconti** [comment]
Hey @znmeb, thanks for opening an issue! Also, I love your Pand-Aid project! 💖 

You're right that you'll run into LF vs CRLF issues if you're working in miss matching environments between the host and your docker container. For your case, you can [configure ](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings) git to use `LF` globally.  That way all of your projects that use containers will "just work" out of the box. Having this set correctly is table stakes for working with docker in any project on windows.

This my preferred solution rather adding a `.gitattributes` file because it adheres to this [project's mantra](https://github.com/agconti/cookiecutter-django-rest/issues/364#issuecomment-354171879) which is to have `the slimmest possible boilerplate possible`. This isn't an issue with the project that needs to be patched, but rather an issue with an individual's environment setup. 

Again, thanks for contributing an opening up this issue. It's great that we have this documented if someone runs into this again.

**Comment by adsanz** [comment]
I may add that changing the manage.py from CRLF to LF worked for me.
