### ISSUE TITLE
Travis-CI build fails on fresh install

### ISSUE THREAD

**Issue by Toumask** [agconti/cookiecutter-django-rest#945]
#### What's going wrong?

Travis-CI  is failing (exited with 1).

`The command "docker-compose run --rm web bash -c "flake8 . && python wait_for_postgres.py && ./manage.py test"" exited with 1.`

I have done some research and I think the problem is in the permission `./manage.py test`, but I dont know how to fix it.

`The command "docker-compose run --rm web bash -c "flake8 . && python wait_for_postgres.py && ./manage.py test"" exited with 126.`

piedpiper-web is also failing (https://travis-ci.org/github/agconti/piedpiper-web). for the same reason.

#### How can the `cookiecutter-django-rest` team reproduce the problem?

a fresh install (using the Github install guide) will reproduce the problem. 

#### Is this a problem with a fresh install of the project?

- [ X] Yes
- [ ] No

**Comment by agconti** [comment]
@KrestouferT thanks for opening up an issue! 

The builds pass just fine for this repo: https://travis-ci.org/github/agconti/cookiecutter-django-rest/builds/704290155. 

`pipedpiper-web` is only an example of the output you'd get while using this project. It's not supposed to be used. It's just for illustrative documentation purposes. Its build is failing because its deps are 6 months old as you can see from the github repo. 

I did a fresh install of this project and it worked fine for me. I'm going to close this issue for now. If you're still running into a problem, feel free to reopen it.
